# Generated by Django 4.0.3 on 2022-04-08 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employe_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.student')),
            ],
            bases=('app.student',),
            managers=[
                ('students_proxy', django.db.models.manager.Manager()),
            ],
        ),
    ]
