# Generated by Django 4.0.3 on 2022-04-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_techer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techer',
            old_name='name',
            new_name='user',
        ),
    ]
