# Generated by Django 4.0.3 on 2022-04-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('surname', models.CharField(max_length=23)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField(blank=True)),
                ('test', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
