# Generated by Django 4.0.3 on 2022-04-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll_no',
            new_name='roll_No',
        ),
    ]
